add download script
st-tech/zozo-shift15m pull request #188
Opened 2022-08-01 01:49 UTC by nocotan

- generate json file with tags information
  - https://research.zozo.com/data_release/shift15m/label/iqon_outfits_with_tags.json
- add download script

2022-08-03 06:18 UTC, more-ishy commented
`download_all.sh`と`download_all_wo_set_testdata.sh`には、`scripts/download_shift15m_outfits_with_tags.sh`を載せないという理解で合ってますか？

2022-08-03 09:24 UTC, more-ishy commented
それと`iqon_outfits.json`では`like_num`と`set_id`の値が`str`だったのが、`iqon_outfits_with_tags.json`では`int`に変わっていますね。
`str`と`int`のどちらでも良いと思いますが、互換性を保つのであれば統一はした方が良いと感じました。

2022-08-03 09:26 UTC, more-ishy requested changes
上記コメントの通りです！

2022-08-06 02:27 UTC, nocotan commented
- download_all.shとdownload_all_wo_set_testdata.shを更新しました
- iqon_outfits_with_tags.jsonのlike_numとset_idの値をstrに更新しました

2022-08-06 08:36 UTC, more-ishy approved these changes
LGTM desu

2022-08-08 04:39 UTC, merged